- name: Initial Setup
  hosts: openwrt_router,openwrt_APs
  gather_facts: false

  roles:
    - community.openwrt.init
    - initial_setup

- name: Change WAN DNS Settings
  hosts: openwrt_router
  gather_facts: false

  roles:
    - community.openwrt.init
    - wan_dns

- name: Setup Cake Autorate on WAN interface
  hosts: openwrt_router
  gather_facts: false

  roles:
    - community.openwrt.init
    - cake_autorate

- name: Configure AP Networks
  hosts: openwrt_APs
  gather_facts: false

  roles:
    - community.openwrt.init
    - ap_network

- name: Configure Wi-Fi
  hosts: openwrt_router,openwrt_APs
  gather_facts: false

  roles:
    - community.openwrt.init
    - wifi

- name: Setup DDNS
  hosts: openwrt_router
  gather_facts: false

  roles:
    - community.openwrt.init
    - ddns

- name: Setup WireGuard VPN Server
  hosts: openwrt_router
  gather_facts: false

  roles:
    - community.openwrt.init
    - wireguard

- name: Setup Tailscale Subnet Router
  hosts: openwrt_router
  gather_facts: false

  roles:
    - community.openwrt.init
    - tailscale

- name: Setup Prometheus Exporter
  hosts: openwrt_router
  gather_facts: false

  roles:
    - community.openwrt.init
    - prometheus_exporter